### PR TITLE
Fix clippy warnings

### PR DESCRIPTION
**Pull request by greizgh**
TODO:
- [x] Fix derive_hash_xor_eq
- [x] Fix or_fun_call

### CODE REVIEW

**Comment by msanders** [comment]
Looks good. I'm seeing the following compilation error on macOS though:

```
error[E0277]: the trait bound `&T: key::KeyCodeConvertible` is not satisfied
   --> src/key.rs:138:5
    |
138 |     system_toggle(key, down, &appended_flags, modifier_delay_ms);
    |     ^^^^^^^^^^^^^ the trait `key::KeyCodeConvertible` is not implemented for `&T`
    |
note: required by `key::system_toggle`
   --> src/key.rs:320:1
    |
320 | / fn system_toggle<T: KeyCodeConvertible>(
321 | |     key: T,
322 | |     down: bool,
323 | |     flags: &[Flag],
...   |
344 | |     event.post(CGEventTapLocation::HID);
345 | | }
    | |_^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: Could not compile `autopilot`.
```

Added support for a build matrix on CI so it's easy to reproduce.

**Comment by greizgh** [comment]
Thanks for your feedback, I'm working on it

**Comment by greizgh** [comment]
This should be fixed!

**Comment by msanders** [comment]
Thanks!

**Pull request merged**
